fixtures:
  forge_modules:
    concat: "puppetlabs/concat"
    inifile: "puppetlabs/inifile"
    stdlib: "puppetlabs/stdlib"
  repositories:
    puppet: "git://github.com/puppetlabs-operations/puppet-puppet"
  symlinks:
    hiera: "#{source_dir}"
